version: "3"
services:
  database:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
