import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { auth } from "@/lib/auth";

import { Providers } from "./_components/providers";
import { Header } from "./_components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col bg-background">
            <Header />
            <main className="container pt-10">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
